import os
import re
import pyautogui
import time
from pynput.keyboard import Controller, Key
import pytesseract
from PIL import Image
import PIL.Image
import cv2
import functions as fu


def dark_dungons():
    fu.wait(0.5)
    fu.select_hero(11)
    fu.wait(0.5)
    fu.select_map(1)
    fu.wait(5)
    fu.place(1088, 929, 'u')
    fu.place(249, 815, 'g')
    fu.start()
    fu.upgrade_time(1, 3)
    fu.upgrade_time(0, 1)
    fu.place_cost(782, 983, 'g')
    fu.upgrade_time(1, 3)
    fu.upgrade_time(0, 1)
    fu.select_monkey(1)
    fu.upgrade_time(1, 1)
    fu.place_cost(177, 394, 'j')
    fu.place_cost(915, 560, 'j')
    fu.place_cost(1424, 330, 'j')
    fu.upgrade_ability2(0, 2, '3', '2')
    fu.upgrade_ability2(1, 3, '3', '2')
    fu.select_monkey(3)
    fu.upgrade_ability2(0, 2, '3', '2')
    fu.upgrade_ability2(1, 3, '3', '2')
    fu.select_monkey(4)
    fu.upgrade_ability2(0, 2, '3', '2')
    fu.upgrade_ability2(1, 3, '3', '2')
    fu.select_monkey(2)
    fu.upgrade_ability(1, 1, '2')
    fu.select_monkey(5)
    fu.upgrade_ability2(1, 1, '3', '2')
    fu.select_monkey(4)
    fu.upgrade_ability2(1, 1, '3', '2')
    fu.select_monkey(3)
    fu.upgrade_ability2(1, 1, '3', '2')
    fu.select_monkey(1)
    fu.upgrade_ability2(1, 1, '3', '2')
    fu.select_monkey(4)
    fu.upgrade_ability2(1, 1, '3', '2')
    fu.finish_map()
       
def heli_Sanctuary():
    fu.wait(0.5)
    fu.select_map(2)
    fu.wait(5)
    fu.place(1300, 500, 'b')
    pyautogui.moveTo(850, 400, duration=0.2)
    fu.start()
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 2)
    fu.upgrade_time(0, 3)
    fu.finish_map()

def ravine():
    fu.wait(0.5)
    fu.select_hero(6)
    fu.wait(0.5)
    fu.select_map(3)
    fu.wait(5)
    fu.place(1550, 363, 'u')
    fu.place(731, 817, 'g')
    fu.start()
    fu.upgrade_time(0, 1)
    fu.upgrade_time(1, 3)
    fu.place_cost(331, 719, 'g')
    fu.upgrade_time(0, 1)
    fu.upgrade_time(1, 3)
    fu.select_monkey(1)
    fu.upgrade_time(1, 1)
    fu.select_monkey(2)
    fu.upgrade_time(1, 1)
    fu.place_cost(509, 797, 'k')
    fu.upgrade_time(1, 2)
    fu.upgrade_time(0, 2)
    fu.place_cost(836, 983, 'j')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 4)
    fu.select_monkey(1)
    fu.upgrade_time(1, 1)
    fu.select_monkey(4)
    fu.upgrade_time(1, 1)
    fu.place_cost(663, 542, 'x')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 5)
    fu.finish_map()

def flooded_valleey():
    fu.wait(0.5)
    fu.select_hero(10)
    fu.wait(0.5)
    fu.select_map(4)
    fu.wait(5)
    fu.place(1182, 487, 'u')
    fu.place(1049, 754, 'c')
    fu.start()
    fu.upgrade_time(2, 2)
    fu.upgrade_time(1, 2)
    fu.place_cost(1020, 170, 'c')
    fu.upgrade_time(1, 2)
    fu.upgrade_time(0,4)
    fu.select_monkey(1)
    fu.upgrade_time(1, 2)
    fu.place_cost(916, 86, 'x')
    fu.upgrade_time(0, 3)
    fu.select_monkey(1)
    fu.upgrade_time(1, 1)
    fu.select_monkey(2)
    fu.upgrade_time(0, 1)
    fu.place_cost(1306, 500, 'x')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 5)
    fu.finish_map()
    
def infernal():
    fu.wait(0.5)
    fu.select_map(5)
    fu.wait(5)
    fu.place(1580, 520, 'y')
    fu.upgrade_time(1, 2) 
    fu.upgrade_time(2, 1)
    fu.start()
    fu.upgrade_time(2, 3)
    fu.place_cost(1580, 620, 'f')
    fu.upgrade_time(0, 4)
    fu.upgrade_time(2, 1)
    fu.select_monkey(0)
    fu.upgrade_time(2, 1)
    fu.select_monkey(1)
    fu.upgrade_time(0, 1)
    fu.finish_map()

def bloody_puddles():
    fu.wait(0.5)
    fu.select_hero(6)
    fu.wait(0.5)
    fu.select_map(6)
    fu.wait(5)
    fu.place(1580, 234, 'u')
    fu.place(495, 675, 'x')
    fu.upgrade_time(0, 1)
    fu.start()
    fu.place_cost(1190, 194, 'x')
    fu.wait(15)
    fu.sell_truck()
    fu.place_cost(796, 674, 'y')
    fu.upgrade_time(1, 2)
    fu.upgrade_time(2, 3)
    fu.place_cost(727, 568, 'y')
    fu.upgrade_time(0,1)
    fu.upgrade_time(2, 2)
    fu.setstrong()
    fu.select_monkey(3)
    fu.upgrade_time(2, 2)
    fu.place_cost(894, 634, 'k')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 3)
    fu.place_cost(882, 725, 'j')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 5)
    fu.select_monkey(1)
    fu.upgrade_time(0, 1)
    fu.upgrade_time(1, 5)
    fu.finish_map()
    

def workshop():
    fu.wait(0.5)
    fu.select_hero(4)
    fu.wait(0.5)
    fu.select_map(7)
    fu.wait(5)
    fu.place(1018, 492, 'u')
    fu.place(607, 460, 'b')
    fu.start()
    pyautogui.moveTo(1095, 550)
    fu.lock_heli()
    fu.upgrade_time(1, 2)
    fu.upgrade_time(2, 2)
    fu.place_cost(1001, 406, 's')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 2)
    fu.place_cost(1577, 680, 'j')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(2, 4)
    fu.select_monkey(1)
    fu.upgrade_time(2, 1)
    fu.select_monkey(2)
    fu.upgrade_time(0,1)
    fu.place_cost(774, 445, 'k')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 3)
    fu.select_monkey(3)
    fu.upgrade_time(2, 1)
    fu.place_cost(919, 480, 'g')
    fu.upgrade_time(0, 1)
    fu.upgrade_time(1, 5)
    fu.finish_map()
    
def quad():
    fu.wait(0.5)
    fu.select_hero(12)
    fu.wait(0.5)
    fu.select_map(8)
    fu.wait(5)
    fu.place(1260, 560, 'u')
    fu.place(450, 560, 'l')
    fu.upgrade_time(1, 1)
    fu.start()
    fu.upgrade_time(2, 4)
    fu.replace_trap(210, 560)
    fu.place_cost(1150, 560, 'l')
    fu.upgrade_time(1, 1)
    fu.upgrade_time(2, 4)
    fu.replace_trap(1450, 560)
    fu.place_cost(820, 460, 'c')
    fu.upgrade_time(1, 2)
    fu.upgrade_time(0, 4)
    fu.place_cost(970, 380, 'k')
    fu.upgrade_time(1, 2)
    fu.upgrade_time(0, 2)
    fu.select_monkey(3)
    fu.upgrade_time(0, 1)
    fu.place_cost(1048, 450, 'y')
    fu.upgrade_time(1, 2)
    fu.upgrade_time(2, 5)
    fu.select_monkey(4)
    fu.upgrade_time(1, 1)
    fu.place_cost(890, 575, 'x')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 5)
    fu.place_cost(1120, 250, 'j')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 5)
    fu.finish_map()

def dark_castle():
    fu.wait(0.5)
    fu.select_hero(4)
    fu.wait(0.5)
    fu.select_map(9)
    fu.wait(5)
    fu.place(546, 472, 'z')
    fu.place(1459, 567, 'm')
    fu.place(778, 446, 'u')
    fu.start()
    fu.select_monkey(1)
    fu.darling_lock()
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 2)
    fu.place_cost(1570, 562, 'j')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(2, 3)
    fu.select_monkey(1)
    fu.upgrade_time(0, 2)
    fu.select_monkey(3)
    fu.upgrade_time(2, 2)
    fu.place_cost(1563, 686, 'f')
    fu.upgrade_time(0, 4)
    fu.upgrade_time(1, 2)
    fu.select_monkey(1)
    fu.upgrade_time(0, 1)
    fu.finish_map()
    
def muddy_puddles():
    fu.wait(0.5)
    fu.select_hero(6)
    fu.wait(0.5)
    fu.select_map(10)
    fu.wait(5)
    fu.place(760, 1040, 'y')
    fu.upgrade_time(1, 2)
    fu.upgrade_time(2, 1)
    fu.start()
    fu.place_cost(971, 893, 'y')
    fu.setstrong()
    fu.upgrade_time(0, 1)
    fu.upgrade_time(2, 2)
    fu.select_monkey(0)
    fu.upgrade_time(2, 3)  
    fu.place_cost(888, 1040, 'f')
    fu.upgrade_time(0, 4)
    fu.upgrade_time(2, 1)
    fu.select_monkey(0)
    fu.upgrade_time(2, 1) 
    fu.place_cost(850, 900, 'k')
    fu.upgrade_time(1, 3)
    fu.upgrade_time(0, 2)
    fu.place_cost(777, 716, 'x')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 5) 
    fu.place_cost(620, 900, 'j')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 5)
    fu.finish_map()

def ouch():
    fu.wait(0.5)
    fu.select_hero(10)
    fu.wait(0.5)
    fu.select_map(11)
    fu.wait(5)
    fu.place(849, 535, 'u')
    fu.place(959, 607, 'c')
    fu.start()
    fu.place_cost(746, 609, 'c')
    fu.select_monkey(1)
    fu.upgrade_time(2, 2)
    fu.upgrade_time(1, 2)
    fu.select_monkey(2)
    fu.upgrade_time(1, 2)
    fu.upgrade_time(0, 4)
    fu.select_monkey(1)
    fu.upgrade_time(1, 2)
    fu.place_cost(1017, 776, 'y')
    fu.upgrade_time(1, 2)
    fu.upgrade_time(2, 5)
    fu.select_monkey(1)
    fu.upgrade_time(1, 1)
    fu.select_monkey(2)
    fu.upgrade_time(0, 1)
    fu.place_cost(849, 784, 'k')
    fu.upgrade_time(0, 1)
    fu.upgrade_time(1, 3)
    fu.place_cost(851, 617, 'x')
    fu.upgrade_time(0, 2)
    fu.upgrade_time(1, 5)
    fu.finish_map()